CREATE TABLE IF NOT EXISTS AccessLog (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER NOT NULL,
    loginDateTime TEXT NOT NULL,
    logoutDateTime TEXT,
    FOREIGN KEY (userId) REFERENCES User(id)
);